export enum ModalAnimation {
  Bounce = 'bounce',
  Flash = 'flash',
  Jello = 'jello',
  Pulse = 'pulse',
  Rotate = 'rotate',
  RubberBand = 'rubberBand',
  Shake = 'shake',
  Swing = 'swing',
  Tada = 'tada',
  Wobble = 'wobble',
  BounceIn = 'bounceIn',
  BounceInDown = 'bounceInDown',
  BounceInUp = 'bounceInUp',
  BounceInLeft = 'bounceInLeft',
  BounceInRight = 'bounceInRight',
  BounceOut = 'bounceOut',
  BounceOutDown = 'bounceOutDown',
  BounceOutUp = 'bounceOutUp',
  BounceOutLeft = 'bounceOutLeft',
  BounceOutRight = 'bounceOutRight',
  FadeIn = 'fadeIn',
  FadeOut = 'fadeOut',
  SlideInUp = 'slideInUp',
  SlideInDown = 'slideInDown',
}
