export interface AboutUs {
  title: string;
  content: string;
}

export const aboutUs: AboutUs = {
  title: 'MCES&FS',
  content:
    "We are a team of passionate people whose goal is to improve everyone's life through disruptive products. We build great products to solve your business problems. Our products are designed for small to medium size companies willing to optimize their performance. We love what we do and we do it with passion. We look forward to working with you. We are a team of passionate people whose goal is to improve everyone's life through disruptive products. We build great products to solve your business problems. Our products are designed for small to medium size companies willing to optimize their performance. We love what we do and we do it with passion. We look forward to working with you. We are a team of passionate people whose goal is to improve everyone's life through disruptive products. We build great products to solve your business problems. Our products are designed for small to medium size companies willing to optimize their performance. We love what we do and we do it with passion. We look forward to working with you. We are a team of passionate people whose goal is to improve everyone's life through disruptive products. We build great products to solve your business problems. Our products are designed for small to medium size companies willing to optimize their performance. We love what we do and we do it with passion. We look forward to working with you. We are a team of passionate people whose goal is to improve everyone's life through disruptive products. We build great products to solve your business problems. Our products are designed for small to medium size companies willing to optimize their performance. We love what we do and we do it with passion. We look forward to working with you. We are a team of passionate people whose goal is to improve everyone's life through disruptive products. We build great products to solve your business problems. Our products are designed for small to medium size companies willing to optimize their performance. We love what we do and we do it with passion. We look forward to working with you. We are a team of passionate people whose goal is to improve everyone's life through disruptive products. We build great products to solve your business problems. Our products are designed for small to medium size companies willing to optimize their performance. We love what we do and we do it with passion. We look forward to working with you. We are a team of passionate people whose goal is to improve everyone's life through disruptive products. We build great products to solve your business problems. Our products are designed for small to medium size companies willing to optimize their performance. We love what we do and we do it with passion. We look forward to working with you.",
};
